language: python
branches:
  only:
  - master
install:
- pip install pelican ghp-import python-dateutil gitpython Pillow disqus-python
addons:
  apt:
    packages:
    - asciidoc
    - source-highlight
script:
- make publish github
env:
  global:
  - GH_USER=jduncan-rva
  - GH_REPO=blog
  - GH_BRANCH=gh-pages
  - secure: cHoS9XO5jeGmww1FnpFOUPaoHr1U8qF858UpVf45CAGsru3BIfZWDe/zggo/WnZ0NXdPuGO1PgvlhsgBHK7ZApDXKut7Ev8mmN9m2VqPwcZ4svySeLTQ+XN4cpYRhnbx3BBCSF3ivuZpl2LM348Nj6UUUt839qPN249txV5j9I7kho1dCDHeIoYglayeb75Kg0PDayJNqjWTtea+4hlAt7xXlLbymuFInQhxWaeDPBrzOUCzZhhKoHqx0bpKnvP1w3zEqT4MTAeito7ZYm6u/76IF/01oSGNrt+baeZNrevOXHYSYOe3UG7EstNF8TtYznDxg6hnVq5ZH76dA3JA3A2k8BkE+WcZnIDcblv4JaYI+zE17gvJy3lHyg26Yt4Dp4bo1CofPuZfs1VLI8eK0LSuokIhYwrNDwP3YPB5w++bsS5bfCfqBc1zO+qGxQ1nGRUd/t4g7RfIMilK592NF/MAV/qXXBQNIW0bVYa43KdWd/38fhYyx9vVi7PW6BCzZQKgJ4WGDM29uQaw5KmRwtC1OjsuQjJijYrqyFbLu5DZyFg8qtjgKiYocoqaG0GhRrLT0K8a6ohM2pNrnlAdtqwRdrTFJF4slGUMpmg55GCUABLjqbxCOsQjGZjztWf923UkQVLdrBF8xugw542ulzQaVxkd/cWBuu0a7DPZGLA=
